version: '3'
services:
  wai:
    image: node
    restart: always
    ports:
      - 7200:5500
    volumes:
      - ./:/home/wai
    working_dir: /home/wai
    environment:
      - PORT=5500
      - NODE_ENV=development
    command: >
      bash -c "npm install
      && npm start"
